# Generated by Django 4.2.6 on 2024-01-20 20:48

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=148)),
                ('image', models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='settings.BASE_DIR'), upload_to='media/benefits/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
            ],
            options={
                'verbose_name': 'Преимущества',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\ttinv'), upload_to='media/brands/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])])),
            ],
            options={
                'verbose_name': 'Бренды',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории каталогов',
                'verbose_name_plural': 'Категории каталогов',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('image', models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\ttinv'), upload_to='media/deliveries/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])])),
                ('path', models.CharField(blank=True, max_length=64)),
                ('link', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('image', models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\ttinv'), upload_to='media/products/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])])),
                ('link', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=148)),
                ('inn', models.CharField(max_length=148)),
                ('email', models.CharField(blank=True, max_length=148)),
                ('message', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name': 'Запросы',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование реквизита')),
                ('value', models.CharField(blank=True, max_length=128, verbose_name='Содержание реквизита')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Группа каталога')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_card.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Группа каталогов',
                'verbose_name_plural': 'Группа каталогов',
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование каталога')),
                ('image', models.ImageField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\ttinv'), upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])], verbose_name='Картинка каталога')),
                ('link', models.FileField(null=True, upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_card.categories', verbose_name='Категория')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_card.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Каталоги',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
