# Generated by Django 4.2.6 on 2024-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
