# Generated by Django 4.2.6 on 2024-01-25 18:40

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_alter_benefits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='image',
            field=models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='C:\\Users\\Mike\\Projects\\ttinv'), upload_to='media/benefits/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg'])]),
        ),
    ]
