# Generated by Django 4.2.6 on 2024-01-03 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0002_products_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование группы каталога')),
                ('image', models.FileField(blank=True, default='default/no-image.svg', null=True, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])], verbose_name='Картинка каталога')),
                ('link', models.CharField(blank=True, max_length=128, verbose_name='Ссылка каталога')),
            ],
            options={
                'verbose_name': 'Каталоги',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='CatalogGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Наименование группы каталога')),
                ('caption', models.CharField(blank=True, max_length=128, verbose_name='Загаловок группы каталога')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_card.catalog')),
            ],
            options={
                'verbose_name': 'Каталоги',
                'verbose_name_plural': 'Каталоги',
            },
        ),
    ]
