# Generated by Django 4.2.6 on 2024-02-10 15:41

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_alter_benefits_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='image',
            field=models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/usr/src/ttinv'), upload_to='media/benefits/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/usr/src/ttinv'), upload_to='media/brands/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='catalogs',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/usr/src/ttinv'), upload_to='catalogs/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])], verbose_name='Картинка каталога'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='image',
            field=models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/usr/src/ttinv'), upload_to='media/deliveries/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, default='/static/images/default/no-image.svg', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/usr/src/ttinv'), upload_to='media/products/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'webp'])]),
        ),
    ]
