# Generated by Django 4.2.6 on 2024-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_card', '0003_catalog_cataloggroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Наименование каталога'),
        ),
    ]
